### ISSUE TITLE
Tokens are not visible

### ISSUE THREAD

**Issue by AbhishekJ17** [thermogl/TITokenField#112]
After click on input field list, in token field delegate i'm adding token but it is not visible.

**Comment by thermogl** [comment]
PRs welcome!

**Comment by AbhishekJ17** [comment]
Can you please elaborate?

**Comment by thermogl** [comment]
Feel free to fix the issue and submit a Pull Request. Thanks!

**Comment by AbhishekJ17** [comment]
OK! i want to tap on TITokenfieldview  and type like textfield, because after keyboard hide i want add more tokenfield then tap on TITokenfieldview keyboard is not shown.

**Comment by thermogl** [comment]
I no longer have time to work on this. So if you can solve the issue please do so yourself. Thanks.
