### ISSUE TITLE
Single line mode option

### ISSUE THREAD

**Issue by EricShapiro** [thermogl/TITokenField#43]
It would be nice if there were a single line mode option, where instead of creating more vertical space for the field as tokens are added it scrolled horizontally instead.

**Comment by prem2014** [comment]
@katleta3000  Hey Katleta: could please help me here. What exactly did you do to get the token appear in single line and make it scrollable horizontally.

**Comment by katleta3000** [comment]
@prem2014 Hello, Prem! We finally realized some new widget, so I don't have code anymore, and event can't find id - it wasn't pushed to repo. Sorry. look at layoutTokensInternal as @thermogl said, it was the only function for changing layout

**Comment by prem2014** [comment]
@katleta3000 Thanks for getting back soon. Could you please tell me the new widget you used. Meanwhile I try tweaking the code to meet the need.

**Comment by katleta3000** [comment]
@prem2014 We realized new widget for new design indoors, unfortunetly it is not public!

**Comment by prem2014** [comment]
@thermogl I am pretty new to IOS, so could you please make the changes and push it in new branch: which is good good for single line and is horizontally scrollable.

**Comment by thermogl** [comment]
I have no need for single line, so if you want me to make those changes, you can hire me to do so ;)
