### ISSUE TITLE
UILineBreakModeTailTruncation deprecated in iOS 6

### ISSUE THREAD

**Issue by y0hnn** [thermogl/TITokenField#59]
Hello !

Just a warning : 

TITokenField.m:987:40: 'UILineBreakModeTailTruncation' is deprecated: first deprecated in iOS 6.0

Thanks !

**Comment by Goyohol** [comment]
typedef NS_ENUM(NSInteger, NSLineBreakMode) {        /* What to do with long lines */
        NSLineBreakByWordWrapping = 0,         /* Wrap at word boundaries, default */
        NSLineBreakByCharWrapping,        /* Wrap at character boundaries */
        NSLineBreakByClipping,        /* Simply clip */
        NSLineBreakByTruncatingHead,    /* Truncate at head of line: "…wxyz" */
        NSLineBreakByTruncatingTail,    /* Truncate at tail of line: "abcd…" */
        NSLineBreakByTruncatingMiddle    /* Truncate middle of line:  "ab…yz" */
    } NS_ENUM_AVAILABLE_IOS(6_0)



we use now!
