### ISSUE TITLE
Tokens center alignment

### ISSUE THREAD

**Issue by saadhre** [thermogl/TITokenField#99]
Is it possible to center align the tokens? I meant something like this:

![zrzut ekranu 2015-05-13 o 20 23 59 1](https://cloud.githubusercontent.com/assets/3045021/7617935/e26c208e-f9ae-11e4-89c3-149037e0848f.png)

**Comment by thermogl** [comment]
Take a look in the layoutTokensInternal method, all the layout stuff is done in there. It should be trivial to center the tokens instead of laying them out to the left.
